### Kaggle PyTorch Tutorial

In [5]:
import torch
import numpy as np

### Tensor

Tensors are matrix like data structures which are essential components in deep learning libraries and efficient computation. GPUs are especially effective at calculating operations between tensors and this has spurred the surge in deep learning capability in recent times.

In [2]:
#Constructing a 5x3 Matrix Uninitialized
x = torch.empty(5,3)
print(x)

tensor([[ 0.0000, -0.0000,  0.0000],
        [-0.0000,  0.0000,  0.0000],
        [ 0.0000,  0.0000,  0.0000],
        [ 0.0000,  0.0000,  0.0000],
        [ 0.0000,  0.0000,  0.0000]])


In [3]:
#Convert to numpy
x.numpy()

array([[ 0.0e+00, -0.0e+00,  0.0e+00],
       [-0.0e+00,  1.4e-44,  0.0e+00],
       [ 0.0e+00,  0.0e+00,  0.0e+00],
       [ 0.0e+00,  0.0e+00,  0.0e+00],
       [ 0.0e+00,  0.0e+00,  0.0e+00]], dtype=float32)

In [4]:
#Size of tensor
x.size()

torch.Size([5, 3])

In [6]:
#From Numpy to tensor
a = np.array([[3,4],[4,3]])
b = torch.from_numpy(a)
print(b)

tensor([[3, 4],
        [4, 3]])


#### Tensor Operations

In [7]:
#Random Similar to Numpy
x = torch.rand(5,3)
print(x)

tensor([[0.0712, 0.4236, 0.4586],
        [0.4990, 0.9752, 0.4019],
        [0.6712, 0.8402, 0.9017],
        [0.7898, 0.7110, 0.7466],
        [0.7227, 0.7289, 0.8619]])


In [10]:
#Construct a matrix filled zeros and of dtype long
x = torch.zeros(5,3, dtype=torch.long)
print(x)

tensor([[0, 0, 0],
        [0, 0, 0],
        [0, 0, 0],
        [0, 0, 0],
        [0, 0, 0]])


In [11]:
x = torch.ones(3,3,dtype=torch.long)
print(x)

tensor([[1, 1, 1],
        [1, 1, 1],
        [1, 1, 1]])


In [12]:
#Construct a Tensor Directly from data
x = torch.tensor([2.5, 7])
print(x)

tensor([2.5000, 7.0000])


In [13]:
#Create Tensor based on existing tensor
x = x.new_ones(5,3, dtype = torch.double)
print(x)
print(x.size())

tensor([[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]], dtype=torch.float64)
torch.Size([5, 3])


In [14]:
x = torch.randn_like(x, dtype=torch.float)
print(x)
print(x.size())

tensor([[-1.0812, -0.6023, -0.2009],
        [-0.8946,  1.1460, -0.1527],
        [-0.7967, -1.2815, -0.6328],
        [-0.1852, -0.4925,  0.3003],
        [ 0.7516, -0.4257,  0.6923]])
torch.Size([5, 3])


### Basic Tensor Operations

In [15]:
x = torch.rand(5,3)
y = torch.rand(5,3)

print(x+y) # old method
print(torch.add(x, y)) # new method

tensor([[1.1454, 1.6373, 0.6299],
        [1.0660, 0.8643, 0.5708],
        [0.7958, 1.1046, 0.5513],
        [1.1956, 1.2745, 0.9629],
        [0.9990, 1.3226, 1.0982]])
tensor([[1.1454, 1.6373, 0.6299],
        [1.0660, 0.8643, 0.5708],
        [0.7958, 1.1046, 0.5513],
        [1.1956, 1.2745, 0.9629],
        [0.9990, 1.3226, 1.0982]])


In [16]:
x = torch.rand(5,3)
y = torch.rand(5,3)
print(x-y) #old method
print(torch.sub(x,y)) #new method

tensor([[ 0.1031, -0.4736,  0.0399],
        [-0.2063,  0.1103,  0.2393],
        [ 0.0936,  0.1453,  0.5804],
        [ 0.1050, -0.5389, -0.2557],
        [ 0.5181,  0.7308, -0.0297]])
tensor([[ 0.1031, -0.4736,  0.0399],
        [-0.2063,  0.1103,  0.2393],
        [ 0.0936,  0.1453,  0.5804],
        [ 0.1050, -0.5389, -0.2557],
        [ 0.5181,  0.7308, -0.0297]])


In [17]:
x = torch.rand(5,3)
y = torch.rand(5,3)
print(x/y) #old method
print(torch.div(x,y)) #new method

tensor([[0.7615, 0.6403, 0.7220],
        [0.2847, 1.4486, 2.8432],
        [0.3599, 0.0794, 1.3748],
        [0.6004, 0.7895, 0.9554],
        [0.0237, 1.4722, 1.1348]])
tensor([[0.7615, 0.6403, 0.7220],
        [0.2847, 1.4486, 2.8432],
        [0.3599, 0.0794, 1.3748],
        [0.6004, 0.7895, 0.9554],
        [0.0237, 1.4722, 1.1348]])


In [18]:
x = torch.rand(5,3)
y = torch.rand(5,3)
print(x*y) #old method
print(torch.mul(x, y)) #new method

tensor([[0.4206, 0.0924, 0.1145],
        [0.6642, 0.4903, 0.0090],
        [0.0643, 0.0450, 0.5209],
        [0.3711, 0.2475, 0.0939],
        [0.0494, 0.1897, 0.3984]])
tensor([[0.4206, 0.0924, 0.1145],
        [0.6642, 0.4903, 0.0090],
        [0.0643, 0.0450, 0.5209],
        [0.3711, 0.2475, 0.0939],
        [0.0494, 0.1897, 0.3984]])


In [19]:
#Adds x to y
#New Value is now inside y
y.add_(x)
print(y)

tensor([[1.2978, 0.8710, 0.8451],
        [1.6340, 1.4689, 0.2128],
        [0.5093, 0.4246, 1.4618],
        [1.2563, 1.0148, 0.6347],
        [0.5006, 1.0808, 1.2776]])


In [21]:
#Standard Numpy like indexing
print(x[:, 1])

tensor([0.7474, 0.5129, 0.2220, 0.4076, 0.8603])


In [22]:
#Resizing
x = torch.randn(4,4)
y = x.view(16)
z = x.view(-1, 8) # The Size -1 is inferred from other dimensions
print(x.size(), y.size(), z.size())

torch.Size([4, 4]) torch.Size([16]) torch.Size([2, 8])


### Variable

The difference between pytorch and numpy is that is provides automatic derivation, which can automatically give you the gradient of the parameters you want. This operation is provided by another basic element, Variable

A variable wraps a Tensor. It supports nearly all the APIs defined by a Tensor. Variable also provides a backward method to perform backpropagation. For example, to backpropagate a loss function to train model parameter x, we use a variable loss to store the value computed by a loss function. Then, we call loss.backward which computes the gradient ∂loss∂x for all the trainable parameters. Pytorch will store the gradient results back in the corresponding variable x

Variable in torch is to build a computational graph, but this graph is dynamic compared with a static graph in tensorflow or theano. So torch does not have placeholder, torch can just pass variable to the computational graph

In [23]:
import torch
from torch.autograd import Variable

In [24]:
#Build a tensor
#Build a variable, usually for compute gradients

tensor = torch.FloatTensor([[1,2], [3,4]])
variable = Variable(tensor, requires_grad=True)

print(tensor)
print(variable)

tensor([[1., 2.],
        [3., 4.]])
tensor([[1., 2.],
        [3., 4.]], requires_grad=True)


Till now the tensor and variable seem the same. However, the variable is a part of the graph, its a part of the auto-gradient

In [25]:
t_out = torch.mean(tensor*tensor)
v_out = torch.2(variable*variable)

print(t_out)
print(v_out)

tensor(7.5000)
tensor(7.5000, grad_fn=<MeanBackward1>)


* Backpropagation from v_out
* v_out = 1/4 * sum(variable * variable)
* the gradients with respect to the variable d(v_out)/d(variable) = 1/4 * 2 * variable = variable/2

In [26]:
v_out.backward()
print(variable.grad)

tensor([[0.5000, 1.0000],
        [1.5000, 2.0000]])


This is data in variable format

In [30]:
print(variable)

tensor([[1., 2.],
        [3., 4.]], requires_grad=True)
